<footer class="m-footer">
    <span class="tit3 w3-card-4 w3-theme-d4">Creaciones Julieth</span>
    <div class="w3-container w3-row">
        <div class="w3-container w3-quarter">
            <h5 class="w3-text-deep-orange w3-center">Datos de Contacto</h5>
            <div class="m-list-footer"><span class="negri">Teléfono: </span>5710604</div>
            <div class="m-list-footer"><span class="negri">Email: </span>creacionesjuliethuniformes@hotmail.com</div>
            <div class="m-list-footer"><span class="negri">Dirección: </span> Localidad de Kennedy(Diag. al INEM) Bogotá DC <br> Calle 38C Sur No. 79A-05</div>

            <h5 class="w3-text-deep-orange w3-center">Punto de Fábrica</h5>
            <div class="m-list-footer"><span class="negri">Teléfono: </span>5710604</div>
            <div class="m-list-footer"><span class="negri">Dirección: </span>Cra80F No. 41-17 Sur<br>Bogotá DC</div>

            <h5 class="w3-text-deep-orange w3-center">Asesor de Venta</h5>
            <div class="m-list-footer"><span class="negri">CARLOS OSMA</span></div>
            <div class="m-list-footer"><span class="negri">Celular: </span>312 554 5605 - 315 583 0651</div>
            <div class="m-list-footer"><span class="negri">Dirección: </span>Cra80F No. 41-17 Sur Bogotá DC</div>
        </div>
        <div class="w3-container w3-half">
            <h5 class="w3-text-deep-orange w3-center">Creadores de Rapid Jackets</h5>
                <div class="w3-accordion m-autores">
                    <!-- -------------------------------------------------------------- -->
                    <button class="w3-btn-block w3-theme-d4 w3-left-align w3-tiny" onclick="acordeon('admin1')"><span class="negri">Anderson Steevenn Garcia</span></button>
                    <div class="w3-accordion-content w3-container" id="admin1">
                        <div class="w3-row w3-container">
                            <img class="m-autor-foto w3-col" src="../media/img/icons_users/bald-user-with-glasses.png">
                            <div class="w3-rest m-auto-desc w3-card-16">
                                <p>Encargado de Proyecto. Responsable de que el proyecto este listo para entregar antes de Quinto trimestre</p>
                            </div>
                        </div>
                    </div>
                    <!-- -------------------------------------------------------------- -->
                    <!-- -------------------------------------------------------------- -->
                    <button class="w3-btn-block w3-theme-d4 w3-left-align w3-tiny" onclick="acordeon('admin2')"><span class="negri">Elkin Fernando Alaguna</span></button>
                    <div class="w3-accordion-content w3-container" id="admin2">
                        <div class="w3-row w3-container">
                            <img class="m-autor-foto w3-col" src="../media/img/icons_users/man-with-low-beard.png">
                            <div class="w3-rest m-auto-desc w3-card-16">
                                <p>Diseñador Gráfico. Encargado de desarrollar las interfaces gráficas o front-end del sistema</p>
                            </div>
                        </div>
                    </div>
                    <!-- -------------------------------------------------------------- -->
                    <!-- -------------------------------------------------------------- -->
                    <button class="w3-btn-block w3-theme-d4 w3-left-align w3-tiny" onclick="acordeon('admin3')"><span class="negri">Josué Francisco Gómez</span></button>
                    <div class="w3-accordion-content w3-container" id="admin3">
                        <div class="w3-row w3-container">
                            <img class="m-autor-foto w3-col" src="../media/img/icons_users/boy-with-glasses.png">
                            <div class="w3-rest m-auto-desc w3-card-16">
                                <p>Desarrollador. Encargado de programar el código fuente de los distintos módulos del aplicativo o back-end</p>
                            </div>
                        </div>
                    </div>
                    <!-- -------------------------------------------------------------- -->
                    <!-- -------------------------------------------------------------- -->
                    <button class="w3-btn-block w3-theme-d4 w3-left-align w3-tiny" onclick="acordeon('admin4')"><span class="negri">Heidy Natalia Carvajal</span></button>
                    <div class="w3-accordion-content w3-container" id="admin4">
                        <div class="w3-row w3-container">
                            <img class="m-autor-foto w3-col" src="../media/img/icons_users/edit-woman-with-bund-profile.png">
                            <div class="w3-rest m-auto-desc w3-card-16">
                                <p>Documentadora. Encargada de documentar el levantamiento de informacion y de hacer seguimiento a las fases de desarrollo del proyecto</p>
                            </div>
                        </div>
                    </div>
                    <!-- -------------------------------------------------------------- -->
                    <!-- -------------------------------------------------------------- -->
                    <button class="w3-btn-block w3-theme-d4 w3-left-align w3-tiny" onclick="acordeon('admin5')"><span class="negri">Angie Jasbleidy Rodríguez</span></button>
                    <div class="w3-accordion-content w3-container" id="admin5">
                        <div class="w3-row w3-container">
                            <img class="m-autor-foto w3-col" src="../media/img/icons_users/woman-with-bund-and-glasses.png">
                            <div class="w3-rest m-auto-desc w3-card-16">
                                <p>Analista. Encargada de hacer el levantamiento de informacion y plantear los requerimientos del sistema.</p>
                            </div>
                        </div>
                    </div>
                    <!-- -------------------------------------------------------------- -->

                </div>
        </div>
        <div class="w3-container w3-quarter">
            <h5 class="w3-text-deep-orange w3-center">Redes Sociales</h5>
            <div class="m-redes-social">
                <a title="Faccebook" href="#"><img class="icon" src="../media/img/icons_social/facebook.png"></a>
                <a title="Instagram" href="#"><img class="icon" src="../media/img/icons_social/instagram.png"></a>
                <a title="Twitter" href="#"><img class="icon" src="../media/img/icons_social/twitter.png"></a>
                <a title="Google Plus" href="#"><img class="icon" src="../media/img/icons_social/google-plus.png"></a>
                <a title="LinkedIn" href="#"><img class="icon" src="../media/img/icons_social/linkedin.png"></a>
            </div>
        </div>
    </div>

</footer>
<script src="../js/vista.js"></script>
<script src="../js/ajax_conections_entities.js"></script>
<script src="controlador/controllers/AjaxManager.js"></script>