<header>
    <div class="m-header">
        <div class="w3-row">
            <div class="w3-quarter w3-container">
                <a href="inicio.php"><img class="m-logo" src="../media/img/logo.png" alt="Logo de Creaciones Julieth" title="Creaciones Julieth"></a>
            </div>
            <div class="w3-threequarter w3-container">
                <div class="tit1">Rapid Jackets</div>
                <span class="tit2">La tienda Online de <i>Creaciones Julieth</i></span>
            </div>
        </div>
        <h3 class="w3-center w3-blue-grey">Uniformes Escolares - Diario y Deportivo - Dotaciones - Programación Bordados - Screen</h3>
    </div>
    <nav class="m-nav" name="UP">
        <a name="UP"></a>
        <ul class="w3-navbar w3-theme-d1">
            <li><a href="inicio.php" class="w3-hover-blue">Inicio</a></li>
            <li><a href="sobre_nosotros.php" class="w3-hover-blue">Sobre Nosotros</a></li>
            <li><a href="productos.php" class="w3-hover-blue">Nuestros productos</a></li>
            <li><a href="contacto.php" class="w3-hover-blue">Contactenos</a></li>
            <li class="w3-right"><a class="w3-hover-green" href="iniciar_sesion.php">Inicie Sesion</a></li>
            <li class="w3-right"><a class="w3-hover-orange" href="registro_usuarios.php">Registrarse</a></li>
            <li class="w3-right"><button class="w3-btn w3-theme-d1 w3-hover-yellow" onclick="verCarritoComprasInModal()"><img src="../media/img/carrito_compra.png" alt="CarritoRapidJackets" title="Ver Carrito Rapid" style="width: 25px;">  Ver carrito</button></li>
        </ul>
    </nav>
    <a href="#UP"><button class="m-boton-go-up">&uparrow;</button></a>
    <div id="CARRITO"></div>
</header>